variables:
  GIT_SSL_NO_VERIFY: "true"
  GIT_DEPTH: "3"
  SECRET_KEY: "pipo"
  REGISTRY: "eur0c.laas.fr:5000"
  DOCKER_TAG: "${REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_NAME}"

format:
  image: gepetto/linters
  before_script:
    - test -f /builds/setup.cfg || ln -s /root/setup.cfg /builds
    - test -f /builds/.clang-format || ln -s /root/.clang-format /builds
  script:
    - flake8 .
    - yapf -dr .

build:
  image: docker
  script:
    - docker build -t ${DOCKER_TAG} .
    - docker run --rm -e SECRET_KEY ${DOCKER_TAG} ./manage.py migrate
    - docker run --rm -e SECRET_KEY ${DOCKER_TAG} ./manage.py test
    - docker push ${DOCKER_TAG}
