variables:
  GIT_SSL_NO_VERIFY: "true"
  GIT_DEPTH: "3"
  SECRET_KEY: "pipo"
  GITHUB_WEBHOOK_KEY: "pipo"
  GITLAB_WEBHOOK_KEY: "pipo"
  REGISTRY: "memmos.laas.fr:5000"
  DOCKER_TAG: "${REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_NAME}"

build:
  image: docker
  script:
    - docker build -t ${DOCKER_TAG} .
    - docker run --rm -e SECRET_KEY -e GITHUB_WEBHOOK_KEY -e GITLAB_WEBHOOK_KEY -e GITHUB_PIPELINE_TOKEN -e GITLAB_PIPELINE_TOKEN -e PYTHONWARNINGS ${DOCKER_TAG} ./manage.py migrate
    - docker run --rm -e SECRET_KEY -e GITHUB_WEBHOOK_KEY -e GITLAB_WEBHOOK_KEY -e GITHUB_PIPELINE_TOKEN -e GITLAB_PIPELINE_TOKEN -e PYTHONWARNINGS ${DOCKER_TAG} ./manage.py test
    - docker push ${DOCKER_TAG}
