variables:
  GIT_SSL_NO_VERIFY: "true"
  GIT_DEPTH: "3"
  SECRET_KEY: "pipo"
  REGISTRY: "eur0c.laas.fr:5000"
  DOCKER_TAG: "${REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_NAME}"

format:
  image: eur0c.laas.fr:5000/gepetto/buildfarm/format:18.04
  script:
    - flake8 .
    - yapf -dr .

build:
  image: docker
  script:
    - docker build -t ${DOCKER_TAG} .
    - docker run --rm -e SECRET_KEY ${DOCKER_TAG} ./manage.py migrate
    - docker run --rm -e SECRET_KEY ${DOCKER_TAG} ./manage.py test
    - docker push ${DOCKER_TAG}
