variables:
  GIT_SSL_NO_VERIFY: "true"
  GIT_DEPTH: "3"
  SECRET_KEY: "pipo"
  REGISTRY: "eur0c.laas.fr:5000"
  DOCKER_TAG: "${REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_NAME}"

format:
  image: python:alpine
  before_script:
    - pip install flake8
  script:
    - flake8 .

build:
  image: docker
  script:
    - docker build -t ${DOCKER_TAG} .
    - docker run --rm -e SECRET_KEY ${DOCKER_TAG} ./manage.py migrate
    - docker run --rm -e SECRET_KEY ${DOCKER_TAG} ./manage.py test
    - docker push ${DOCKER_TAG}
