ARG TARGET
ARG REGISTRY=eur0c.laas.fr:4567
ARG FROM=gsaurel/buildfarm/robotpkg

FROM ${REGISTRY}/${FROM}:${TARGET}

ARG ROBOTPKG
ARG ROBOTPKG_DEPS=true
ARG ADDITIONAL_DEPENDENCIES=""
ARG CHECKOUT=false

RUN /get_deps.sh robotpkg-${ROBOTPKG} $CHECKOUT
