version: '3'

volumes:
  static:
  media:

services:
  app:
    build: .
    restart: unless-stopped
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - /srv/dashboard/repositories:/srv/dashboard/repositories
      - /srv/dashboard/robotpkg:/srv/dashboard/robotpkg
      - static:/srv/static
      - media:/srv/media
    env_file:
      - .env
  nginx:
    image: nim65s/ndh:nginx
    restart: unless-stopped
    volumes:
      - static:/srv/static
      - media:/srv/media
    ports:
      - 6500:8000
