version: '3'

services:
  app:
    build: .
    volumes:
      - ./db.sqlite3:./db.sqlite3
      - /srv/dashboard/repositories:/srv/dashboard/repositories
      - /srv/dashboard/robotpkg:/srv/dashboard/robotpkg
    ports:
      - '8001:8000'
    env_file:
      - .env
