version: '3'

volumes:
  srv:
  sql:

services:
  postgres:
    image: postgres:10-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - "sql:/var/lib/postgresql/data"
  memcached:
    image: memcached:alpine
    restart: unless-stopped
  app:
    image: memmos.laas.fr:5000/gepetto/dashboard:master
    build: .
    restart: unless-stopped
    volumes:
      - "srv:/srv"
      - /srv/dashboard/repositories:/srv/dashboard/repositories
      - /srv/dashboard/robotpkg:/srv/dashboard/robotpkg
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/ssmtp:/etc/ssmtp
    env_file:
      - .env
    environment:
      - DB=postgres
      - MEMCACHED=True
    networks:
      - web
      - default
    labels:
      traefik.enable: "true"
      traefik.http.routers.rainboard-app.rule: "Host(`rainboard.${DOMAIN_NAME:-localhost}`)"
  nginx:
    image: nim65s/ndh
    restart: unless-stopped
    volumes:
      - "srv:/srv"
    networks:
      - web
    labels:
      traefik.enable: "true"
      traefik.http.routers.rainboard-ngx.rule: "Host(`rainboard.${DOMAIN_NAME:-localhost}`) && PathPrefix(`/static`, `/media`)"

networks:
  web:
    external: true
