version: '3'

volumes:
  static:
  media:

services:
  app:
    image: eur0c.laas.fr:5000/gepetto/dashboard:master
    restart: unless-stopped
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - /srv/dashboard/repositories:/srv/dashboard/repositories
      - /srv/dashboard/robotpkg:/srv/dashboard/robotpkg
      - static:/srv/static
      - media:/srv/media
    env_file:
      - .env
  nginx:
    image: nim65s/ndh:nginx
    restart: unless-stopped
    volumes:
      - static:/srv/static
      - media:/srv/media
    expose:
      - 8000
    labels:
      - "traefik.backend=dashboard"
      - "traefik.frontend.rule=Host:rainboard.laas.fr"
    networks:
      - web
      - default

networks:
  web:
    external: true
