ARG REGISTRY=eur0c.laas.fr:4567
ARG NAMESPACE=gsaurel/buildfarm
ARG IMAGE=robotpkg
ARG TARGET=14.04

FROM ${REGISTRY}/${NAMESPACE}/${IMAGE}:${TARGET}

ARG ROBOTPKG
ARG ROBOTPKG_DEPS=true
ARG ADDITIONAL_DEPENDENCIES=""
ARG CHECKOUT=false

RUN /get_deps.sh robotpkg-${ROBOTPKG} $CHECKOUT
