# Generated by Django 2.0.1 on 2018-01-05 10:20

import os

from django.db import migrations

import requests

from rainboard.utils import SOURCES


def forges(apps, schema_editor):
    Forge = apps.get_model('rainboard', 'Forge')
    Forge.objects.create(name='Gitlab', source=SOURCES.gitlab, url='https://eur0c.laas.fr', verify=False,
                         token=os.getenv('GITLAB_TOKEN'))
    Forge.objects.create(name='Github', source=SOURCES.github, url='https://github.com',
                         token=os.getenv('GITHUB_TOKEN'))
    Forge.objects.create(name='Redmine', source=SOURCES.redmine, url='https://redmine.laas.fr',
                         token=os.getenv('REDMINE_TOKEN'))
    Forge.objects.create(name='Openrobots', source=SOURCES.redmine, url='https://git.openrobots.org',
                         token=os.getenv('OPENROB_TOKEN'))
    Forge.objects.create(name='Travis', source=SOURCES.travis, url='https://travis-ci.org',
                         token=os.getenv('TRAVIS_TOKEN'))

def groups(apps, schema_editor):
    Namespace = apps.get_model('rainboard', 'Namespace')
    Namespace.objects.create(name='Stack Of Tasks', group=True)
    Namespace.objects.create(name='Humanoid Path Planner', group=True)
    Namespace.objects.create(name='Gepetto', group=True)
    Namespace.objects.create(name='Pyrène Dev', group=True)


class Migration(migrations.Migration):

    dependencies = [
        ('rainboard', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forges),
        migrations.RunPython(groups),
    ]
