# Generated by Django 2.0.1 on 2018-01-29 16:43

import autoslug.fields
from django.db import migrations
import rainboard.utils


class Migration(migrations.Migration):

    dependencies = [
        ('rainboard', '0002_forges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=rainboard.utils.slugify_with_dots),
        ),
    ]
