# Generated by Django 2.0.1 on 2018-01-30 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rainboard', '0004_project_main_forge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='commit',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='repo',
        ),
        migrations.AddField(
            model_name='branch',
            name='ahead',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='behind',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rainboard.Project'),
            preserve_default=False,
        ),
    ]
