# Generated by Django 2.0.1 on 2018-01-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainboard', '0005_branches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='slug',
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
