# Generated by Django 2.0.2 on 2018-02-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rainboard", "0005_contributor_agreement_signed"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
