# Generated by Django 2.0.1 on 2018-01-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rainboard', '0006_auto_20180130_1456'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('project', 'name')},
        ),
    ]
