# Generated by Django 2.0.2 on 2018-02-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainboard', '0006_branch_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='docs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tests',
            field=models.BooleanField(default=True),
        ),
    ]
