# Generated by Django 2.0.2 on 2018-03-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rainboard', '0007_projects_tests_docs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='project',
            name='articles',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
