# Generated by Django 2.0.1 on 2018-01-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainboard', '0008_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
