# Generated by Django 2.0.1 on 2018-01-31 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rainboard', '0009_project_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robotpkgdependency',
            name='project',
        ),
        migrations.AddField(
            model_name='robotpkg',
            name='category',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='robotpkg',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='robotpkg',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='robotpkg',
            name='maintainer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='robotpkg',
            name='master_repository',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='robotpkg',
            name='master_sites',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='robotpkg',
            name='pkgbase',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='robotpkg',
            name='pkgversion',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='robotpkg',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='robotpkg',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='robotpkg',
            name='homepage',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='robotpkg',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rainboard.Project'),
        ),
        migrations.DeleteModel(
            name='RobotpkgDependency',
        ),
    ]
