# Generated by Django 2.0.4 on 2018-04-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rainboard", "0009_branch_keep_doc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="robotpkg",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="repo",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
