# Generated by Django 2.0.1 on 2018-01-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainboard', '0010_robotpkg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
