# Generated by Django 2.0.1 on 2018-02-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainboard', '0011_project_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
