# Generated by Django 2.0.1 on 2018-02-05 13:52

from django.db import migrations, models
import django.db.models.deletion


def populate_branch_repo(apps, schema_editor):
    Branch = apps.get_model('rainboard', 'Branch')
    Repo = apps.get_model('rainboard', 'Repo')

    for branch in Branch.objects.all():
        if branch.name in ['master', 'devel']:
            forge = branch.project.main_forge.slug
            namespace = branch.project.main_namespace.slug
        else:
            forge, namespace = branch.name.split('/')[:2]
        branch.repo = Repo.objects.get(forge__slug=forge, namespace__slug=namespace, project=branch.project)
        branch.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rainboard', '0012_branch_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='repo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rainboard.Repo'),
        ),
        migrations.RunPython(populate_branch_repo),
        migrations.AlterField(
            model_name='branch',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rainboard.Repo'),
        ),
    ]
