# Generated by Django 2.0.1 on 2018-02-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainboard', '0013_branch_repo'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='travis_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
