# Generated by Django 2.0.5 on 2018-06-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rainboard", "0014_py3"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="debug",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="debug",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="image",
            unique_together={("robotpkg", "target", "py3", "debug")},
        ),
    ]
