# Generated by Django 2.0.5 on 2018-06-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rainboard", "0016_blank_robotpkg_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="from_gepetto",
            field=models.BooleanField(default=True),
        ),
    ]
