# Generated by Django 2.0.5 on 2018-07-02 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rainboard", "0017_project_from_gepetto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="target",
            name="python3",
        ),
    ]
