# Generated by Django 2.0.5 on 2018-07-02 09:49

from django.db import migrations


def dubnium_to_erbium(apps, schema_editor):
    Target = apps.get_model("rainboard", "Target")
    Target.objects.filter(name="dubnium").update(active=False)
    Target.objects.create(name="erbium")


class Migration(migrations.Migration):
    dependencies = [
        ("rainboard", "0019_target_active"),
    ]

    operations = [
        migrations.RunPython(dubnium_to_erbium),
    ]
