# Generated by Django 2.0.5 on 2018-07-10 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rainboard', '0020_erbium'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robotpkg', models.BooleanField(default=False)),
                ('cmake', models.BooleanField(default=False)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdeps', to='rainboard.Project')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='rainboard.Project')),
            ],
            options={
                'verbose_name_plural': 'dependencies',
            },
        ),
        migrations.AlterUniqueTogether(
            name='dependency',
            unique_together={('project', 'library')},
        ),
    ]
