# Generated by Django 2.0.5 on 2018-07-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rainboard", "0021_dependency"),
    ]

    operations = [
        migrations.AddField(
            model_name="dependency",
            name="ros",
            field=models.BooleanField(default=False),
        ),
    ]
