# Generated by Django 2.1.3 on 2018-11-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rainboard", "0023_branch_repo"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="cmake_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
