# Generated by Django 2.1.3 on 2018-12-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rainboard", "0024_project_cmake_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="robotpkg",
            name="pkgversion",
            field=models.CharField(default="", max_length=50),
        ),
    ]
