# Generated by Django 2.1.4 on 2019-02-20 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rainboard", "0029_blank_suffix"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="debug",
        ),
    ]
