# Generated by Django 2.1.7 on 2019-03-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rainboard", "0032_cijob"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="allow_format_failure",
            field=models.BooleanField(default=False),
        ),
    ]
