# Generated by Django 2.1.7 on 2019-03-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rainboard", "0033_project_allow_format_failure"),
    ]

    operations = [
        migrations.AddField(
            model_name="dependency",
            name="mandatory",
            field=models.BooleanField(default=True),
        ),
    ]
