# Generated by Django 2.2.4 on 2019-08-08 15:30

from enum import IntEnum

from django.db import migrations


def add_targets(apps, schema_editor):
    Target = apps.get_model("rainboard", "Target")

    # Add stretch
    Target.objects.create(name="stretch", active=True)

    # Disable dubnium, jessie & erbium
    Target.objects.filter(name="dubnium").update(active=False)
    Target.objects.filter(name="jessie").update(active=False)
    Target.objects.filter(name="erbium").update(active=False)

    # Remove old images
    Image = apps.get_model("rainboard", "Image")
    Image.objects.filter(target__active=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("rainboard", "0035_oops"),
    ]

    operations = [
        migrations.RunPython(add_targets),
    ]
