# Generated by Django 3.0.3 on 2020-06-26 16:01

from django.db import migrations


def add_targets(apps, schema_editor):
    Target = apps.get_model('rainboard', 'Target')
    Target.objects.create(name='20.04')


class Migration(migrations.Migration):

    dependencies = [
        ('rainboard', '0042_gepgitlab_to_gitlab'),
    ]

    operations = [
        migrations.RunPython(add_targets),
    ]
