# Generated by Django 3.0.5 on 2020-05-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rainboard", "0042_gepgitlab_to_gitlab"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="from_gepetto",
            field=models.BooleanField(default=False),
        ),
    ]
