# Generated by Django 3.0.8 on 2020-08-04 13:33

from django.db import migrations, models

from rainboard.models import GEPETTO_SLUGS


def update_namespaces(apps, schema_editor):
    Namespace = apps.get_model("rainboard", "Namespace")
    Namespace.objects.filter(slug__in=GEPETTO_SLUGS).update(from_gepetto=True)


class Migration(migrations.Migration):
    dependencies = [
        ("rainboard", "0047_issuepr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="from_gepetto",
        ),
        migrations.AddField(
            model_name="namespace",
            name="from_gepetto",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(update_namespaces),
    ]
