# Generated by Django 3.0.9 on 2020-08-10 08:12

from django.db import migrations, models

def fix_py2(apps, schema_editor):
    Target = apps.get_model('rainboard', 'Target')
    focal = Target.objects.get(name='20.04')
    focal.py2_available = False
    focal.save()
    focal.image_set.filter(py3=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rainboard', '0050_buster'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='py2_available',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(fix_py2),
    ]
