# Generated by Django 3.0.9 on 2020-08-12 09:47

from django.db import migrations


def add_targets(apps, schema_editor):
    Target = apps.get_model('rainboard', 'Target')
    Target.objects.create(name='centos7')


class Migration(migrations.Migration):

    dependencies = [
        ('rainboard', '0051_target_py2_available'),
    ]

    operations = [
        migrations.RunPython(add_targets),
    ]
