# Generated by Django 3.2 on 2021-04-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rainboard", "0054_robotpkg_extended_target"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cibuild",
            name="passed",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="cijob",
            name="passed",
            field=models.BooleanField(null=True),
        ),
    ]
