# Generated by Django 3.2 on 2021-04-29 15:08

from django.db import migrations


def disable_trusty(apps, schema_editor):
    Target = apps.get_model('rainboard', 'Target')
    trusty = Target.objects.get(name='16.04')
    trusty.active = False
    trusty.save()
    Robotpkg = apps.get_model('rainboard', 'Robotpkg')
    for project in ['eigenpy', 'hpp-fcl', 'pinocchio', 'tsid', 'crocoddyl']:
        for rpkg in Robotpkg.objects.filter(project__slug=project):
            rpkg.extended_target.add(trusty)
            rpkg.extended_target.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rainboard', '0055_nullbooleanfield'),
    ]

    operations = [
        migrations.RunPython(disable_trusty),
    ]
