# Generated by Django 3.2.5 on 2021-09-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rainboard", "0059_auto_20210826_1411"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="ccache",
        ),
    ]
