# Generated by Django 3.2.5 on 2021-09-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rainboard", "0062_linters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="clang_format",
            field=models.PositiveSmallIntegerField(default=12),
        ),
    ]
