# Generated by Django 3.2.7 on 2021-09-14 12:07

from django.db import migrations


def main_focal(apps, schema_editor):
    Target = apps.get_model("rainboard", "Target")
    Target.objects.filter(name="18.04").update(main=False)
    Target.objects.filter(name="20.04").update(main=True)


class Migration(migrations.Migration):

    dependencies = [
        ("rainboard", "0063_alter_project_clang_format"),
    ]

    operations = [
        migrations.RunPython(main_focal),
    ]
