# Generated by Django 3.2.7 on 2021-10-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rainboard", "0064_main_focal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="robotpkg",
            name="extended_target",
            field=models.ManyToManyField(blank=True, null=True, to="rainboard.Target"),
        ),
    ]
