# Generated by Django 3.2.12 on 2022-03-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rainboard", "0066_alter_robotpkg_extended_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="clang_default",
            field=models.BooleanField(default=False),
        ),
    ]
