# Generated by Django 3.2.13 on 2022-05-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rainboard", "0067_project_clang_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="clang_default",
            field=models.BooleanField(default=True),
        ),
    ]
