# Generated by Django 3.2.15 on 2022-08-11 09:15

from django.db import migrations, models


def python_version(apps, schema_editor):
    Target = apps.get_model("rainboard", "Target")
    Target.objects.update(python_major=2, python_minor=7)
    Target.objects.filter(name="buster").update(python_major=3, python_minor=7)
    Target.objects.filter(name="20.04").update(python_major=3, python_minor=8)
    Target.objects.create(
        name="bullseye",
        python_major=3,
        python_minor=9,
    )
    Target.objects.create(
        name="22.04",
        python_major=3,
        python_minor=10,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("rainboard", "0068_alter_project_clang_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="target",
            name="python_major",
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="target",
            name="python_minor",
            field=models.SmallIntegerField(default=8),
        ),
        migrations.RunPython(python_version),
    ]
