# Generated by Django 3.2.15 on 2022-08-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rainboard", "0069_auto_20220811_1115"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="min_python_major",
            field=models.SmallIntegerField(default=2),
        ),
    ]
