# Generated by Django 4.2 on 2023-04-21 08:29

from django.db import migrations


def drop_bionic(apps, schema_editor):
    target = apps.get_model("rainboard", "Target")
    bionic = target.objects.get(name="18.04")
    bionic.active = False
    bionic.save()
    robotpkg = apps.get_model("rainboard", "Robotpkg")
    for rpkg in robotpkg.objects.filter(
        project__slug__in=["eigenpy", "hpp-fcl", "pinocchio"],
    ):
        rpkg.extended_target.add(bionic)


class Migration(migrations.Migration):
    dependencies = [
        ("rainboard", "0071_drop_trusty"),
    ]

    operations = [
        migrations.RunPython(drop_bionic),
    ]
