# Generated by Django 4.2.2 on 2023-06-05 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rainboard", "0073_alter_branch_created_alter_commit_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="clang_default",
        ),
        migrations.RemoveField(
            model_name="project",
            name="clang_format",
        ),
    ]
