# Generated by Django 4.2.2 on 2023-06-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rainboard", "0074_remove_project_clang_default_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
