# Generated by Django 4.2.2 on 2023-06-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rainboard", "0075_alter_image_image"),
    ]

    operations = []
