# Generated by Django 4.2.2 on 2023-06-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rainboard", "0075_alter_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="cmake_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="project",
            name="homepage",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="project",
            name="version",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="repo",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="repo",
            name="homepage",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="repo",
            name="url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="robotpkg",
            name="homepage",
            field=models.URLField(blank=True, default=""),
        ),
    ]
