# Generated by Django 4.2.6 on 2023-10-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rainboard", "0078_stop_1804"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="clang_args",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
