# Generated by Django 5.0.2 on 2024-02-15 14:52

from django.db import migrations


def add_bookworm(apps, schema_editor):
    Target = apps.get_model("rainboard", "Target")

    # Add stretch
    Target.objects.create(name="bookworm", active=True)


class Migration(migrations.Migration):
    dependencies = [
        ("rainboard", "0079_project_clang_args"),
    ]

    operations = [
        migrations.RunPython(add_bookworm),
    ]
