# Generated by Django 5.0.2 on 2024-02-15 14:56

from django.db import migrations


def clean_targets(apps, schema_editor):
    Target = apps.get_model("rainboard", "Target")
    Target.objects.filter(name="buster").update(active=False)
    Target.objects.filter(name="ferrum").update(active=False)


class Migration(migrations.Migration):
    dependencies = [
        ("rainboard", "0080_add_bookworm"),
    ]

    operations = [
        migrations.RunPython(clean_targets),
    ]
