# Generated by Django 5.0.2 on 2024-02-16 16:43

from django.db import migrations


def update_targets(apps, schema_editor):
    Target = apps.get_model("rainboard", "Target")
    Target.objects.filter(name="bookworm").update(python_major=3, python_minor=11)
    Target.objects.create(name="archlinux", python_major=3, python_minor=11)


class Migration(migrations.Migration):
    dependencies = [
        ("rainboard", "0081_clean_targets"),
    ]

    operations = [
        migrations.RunPython(update_targets),
    ]
