# Generated by Django 5.0.6 on 2024-07-04 11:02

from django.db import migrations

def add_noble(apps, schema_editor):
    Target = apps.get_model("rainboard", "Target")
    Target.objects.create(
        name="24.04",
        python_major=3,
        python_minor=12,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("rainboard", "0083_main_jammy"),
    ]

    operations = [
        migrations.RunPython(add_noble),
    ]
