# Generated by Django 5.0.6 on 2024-10-07 16:24

import autoslug.fields
from django.db import migrations


def set_slug_us(apps, schema_editor):
    Project = apps.get_model("rainboard", "Project")
    for p in Project.objects.all():
        p.slug_us = p.slug
        p.save()
    for p in Project.objects.filter(name__in=["hpp tutorial", "hpp romeo"]):
        p.slug_us = p.slug.replace("-", "_")
        p.save()


class Migration(migrations.Migration):
    dependencies = [
        ("rainboard", "0084_add_noble"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slug_us",
            field=autoslug.fields.AutoSlugField(
                default="",
                editable=False,
                populate_from="slug",
                unique=False,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_slug_us),
    ]
