# Generated by Django 5.0.6 on 2024-10-07 16:56

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rainboard", "0086_alter_project_slug_us"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug_us",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="slug", unique=True,
            ),
        ),
    ]
