# Generated by Django 5.1.1 on 2025-01-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rainboard", "0087_alter_project_slug_us"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="ignore",
            field=models.BooleanField(default=False),
        ),
    ]
