# Generated by Django 5.2.1 on 2025-05-13 13:34

from django.db import migrations


def drop_focal(apps, schema_editor):
    Target = apps.get_model("rainboard", "Target")
    Target.objects.all().update(main=False)
    Target.objects.filter(name="20.04").update(active=False)
    Target.objects.filter(name="24.04").update(main=True)

class Migration(migrations.Migration):

    dependencies = [
        ("rainboard", "0088_project_ignore"),
    ]

    operations = [
        migrations.RunPython(drop_focal),
    ]
