variables:
  GIT_SSL_NO_VERIFY: "true"
  GIT_SUBMODULE_STRATEGY: "recursive"
  GIT_DEPTH: "3"
  NAMESPACE: {{ project.main_namespace.slug }}
  PROJECT: {{ project }}
  REGISTRY: {{ project.registry }}
  IMAGE: "${REGISTRY}/${NAMESPACE}/${PROJECT}"

cache:
  paths:
    - build/ccache

{% for robotpkg in project.robotpkg_set.all %}
.robotpkg-{{ robotpkg }}: &robotpkg-{{ robotpkg }}
  variables:
    ROBOTPKG: {{ robotpkg }}
    CATEGORY: {{ robotpkg.category }}
  before_script:
    - mkdir -p build/ccache
    - cd build
    - export CCACHE_BASEDIR=${PWD}
    - export CCACHE_DIR=${PWD}/ccache
  script:
    - cd /root/robotpkg/${CATEGORY}/${ROBOTPKG}
    - git pull
    - echo "MASTER_REPOSITORY = git ${CI_PROJECT_DIR}" >> Makefile
    - echo "REPOSITORY.{{ robotpkg }} = git ${CI_PROJECT_DIR}" >> /opt/openrobots/etc/robotpkg.conf
    - make checkout
    - make install
    - cd work.*/${PROJECT}*/
    {% if project.tests %}- make test{% endif %}
    {% if project.docs %}- make doc{% endif %}
  except:
    - gh-pages

{% for image in robotpkg.valid_images %}
robotpkg-{{ image }}:
  <<: *robotpkg-{{ robotpkg }}
  image: ${IMAGE}:{{ image.get_target_display }}
{% endfor %}

{% endfor %}
