variables:
  GIT_SUBMODULE_STRATEGY: "recursive"
  GIT_DEPTH: "3"
  NAMESPACE: {{ project.main_namespace.slug }}
  PROJECT: {{ project }}
  REGISTRY: {{ project.registry }}
  IMAGE: "${REGISTRY}/${NAMESPACE}/${PROJECT}"
  CCACHE_BASEDIR: "$${CI_PROJECT_DIR}"
  CCACHE_DIR: "${CI_PROJECT_DIR}/ccache"

cache:
  paths:
    - ccache

{% for robotpkg in project.robotpkg_set.all %}
.robotpkg-{{ robotpkg }}: &robotpkg-{{ robotpkg }}
  variables:
    ROBOTPKG: {{ robotpkg }}
    CATEGORY: {{ robotpkg.category }}
  before_script:
    - mkdir -p ccache
  script:
    - cd /root/robotpkg/${CATEGORY}/${ROBOTPKG}
    - git pull
    - make install WRKSRC=${CI_PROJECT_DIR}
    - cd ${CI_PROJECT_DIR}
    {% if project.tests %}- make check{% endif %}
    {% if project.docs %}- make doc{% endif %}
  except:
    - gh-pages

{% for image in robotpkg.valid_images %}
robotpkg-{{ image }}:
  <<: *robotpkg-{{ robotpkg }}
  image: ${IMAGE}:{{ image.get_target_display }}
{% if projectsdocs and image.get_target_display == '16.04'%}
  artifacts:
    expire_in: 1 day
    paths:
        - doc/doxygen-html/
{% endif %}
{% endfor %}

{% endfor %}
