variables:
  GIT_SUBMODULE_STRATEGY: "recursive"
  GIT_DEPTH: "3"
  CCACHE_BASEDIR: "${CI_PROJECT_DIR}"
  CCACHE_DIR: "${CI_PROJECT_DIR}/ccache"

cache:
  paths:
    - ccache

{% for robotpkg in project.robotpkg_set.all %}
.robotpkg-{{ robotpkg }}: &robotpkg-{{ robotpkg }}
  except:
    - gh-pages
  before_script:
    - mkdir -p ccache
  script:
    - cd {{ robotpkg.category }}/{{ robotpkg }}
    - git pull
    - make checkout MASTER_REPOSITORY="dir ${CI_PROJECT_DIR}"
    - make install
    - cd work.$(hostname)/$(make show-var VARNAME=DISTNAME)
    {% if project.tests %}- make check{% endif %}
    {% if project.docs %}- make doc
    - mv doc/doxygen-html ${CI_PROJECT_DIR}{% endif %}

{% for image in robotpkg.valid_images %}
robotpkg-{{ image }}:
  <<: *robotpkg-{{ robotpkg }}
  image: {{ image.get_image_name }}
{% if project.docs and image.target.name == '16.04' and not image.py3 %}  artifacts:
    expire_in: 1 day
    paths:
      - doxygen-html/
{% endif %}
{% endfor %}
{% endfor %}
