variables:
  GIT_SUBMODULE_STRATEGY: "recursive"
  GIT_DEPTH: "3"
  NAMESPACE: {{ project.main_namespace.slug }}
  PROJECT: {{ project }}
  REGISTRY: {{ project.registry }}
  IMAGE: "${REGISTRY}/${NAMESPACE}/${PROJECT}"
  CCACHE_BASEDIR: "${CI_PROJECT_DIR}"
  CCACHE_DIR: "${CI_PROJECT_DIR}/ccache"

cache:
  paths:
    - ccache

{% for robotpkg in project.robotpkg_set.all %}
.robotpkg-{{ robotpkg }}: &robotpkg-{{ robotpkg }}
  variables:
    ROBOTPKG: {{ robotpkg }}
    CATEGORY: {{ robotpkg.category }}
  except:
    - gh-pages
  before_script:
    - mkdir -p ccache
  script:
    - cd /root/robotpkg/${CATEGORY}/${ROBOTPKG}
    - git pull
    - make checkout MASTER_REPOSITORY="dir ${CI_PROJECT_DIR}"
    - make install
    - cd work.$(hostname)/$(make show-var VARNAME=DISTNAME)
    {% if project.tests %}- make check{% endif %}
    {% if project.docs %}- make doc
    - mv doc/doxygen-html ${CI_PROJECT_DIR}{% endif %}

{% for image in robotpkg.valid_images %}
robotpkg-{{ image }}:
  <<: *robotpkg-{{ robotpkg }}
  image: ${IMAGE}:{{ image.target }}
{% if project.docs and image.target.name == '16.04' %}  artifacts:
    expire_in: 1 day
    paths:
      - doxygen-html/
{% endif %}
{% endfor %}
{% endfor %}
