variables:
  GIT_SSL_NO_VERIFY: "true"
  GIT_SUBMODULE_STRATEGY: "recursive"
  GIT_DEPTH: "3"
  NAMESPACE: {{ robotpkg.project.main_namespace.slug }}
  PROJECT: {{ robotpkg.project }}
  ROBOTPKG: {{ robotpkg }}
  CATEGORY: {{ robotpkg.category }}
  IMAGE: "${CI_REGISTRY}/${NAMESPACE}/${PROJECT}"

cache:
  paths:
    - build/ccache

.robotpkg-{{ robotpkg }}: &robotpkg-{{ robotpkg }}
  before_script:
    - mkdir -p build/ccache
    - cd build
    - export CCACHE_BASEDIR=${PWD}
    - export CCACHE_DIR=${PWD}/ccache
  script:
    - cd /root/robotpkg/${CATEGORY}/${ROBOTPKG}
    - echo "REPOSITORY=git ${CI_PROJECT_DIR}" >> Makefile
    - make checkout
    - make install
    - cd work.*/${PROJECT}*/
    - make test
  retry: 2
  except:
    - gh-pages

{% for image in robotpkg.valid_images %}
robotpkg-{{ image }}:
  <<: *robotpkg-{{ robotpkg }}
  image: ${IMAGE}:{{ image.get_target_display }}
{% endfor %}
