# Generated by Django 3.0.3 on 2020-02-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GithubCheckSuite",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
